In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('spotify_millsongdata.csv')

In [3]:
print('Raw text sample from CSV:')
print(pd.read_csv('spotify_millsongdata.csv')['text'].head(20))

Raw text sample from CSV:
0     Look at her face, it's a wonderful face  \r\nA...
1     Take it easy with me, please  \r\nTouch me gen...
2     I'll never know why I had to go  \r\nWhy I had...
3     Making somebody happy is a question of give an...
4     Making somebody happy is a question of give an...
5     Well, you hoot and you holler and you make me ...
6     Down in the street they're all singing and sho...
7     Chiquitita, tell me what's wrong  \r\nYou're e...
8     I was out with the morning sun  \r\nCouldn't s...
9     I'm waitin' for you baby  \r\nI'm sitting all ...
10    Oh, my love it makes me sad.  \r\nWhy did thin...
11    You can dance, you can jive, having the time o...
12    Changing, moving in a circle  \r\nI can see yo...
13    You're so hot, teasing me  \r\nSo you're blue ...
14    Agnetha We're not the stars of a Hollywood mov...
15    I can hear how you work, practising hard  \r\n...
16    They came flying from far away, now I'm under ...
17    Every good man needs a helping hand  \r\nso I ...
18    Can you hear the drums Fernando?  \r\nI rememb...
19    Puedes escuchar Fernando?  \r\nMe recuerda tie...
Name: text, dtype: object

In [4]:
df.head(10)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...
5,ABBA,Burning My Bridges,/a/abba/burning+my+bridges_20003011.html,"Well, you hoot and you holler and you make me ..."
6,ABBA,Cassandra,/a/abba/cassandra_20002811.html,Down in the street they're all singing and sho...
7,ABBA,Chiquitita,/a/abba/chiquitita_20002978.html,"Chiquitita, tell me what's wrong \r\nYou're e..."
8,ABBA,Crazy World,/a/abba/crazy+world_20003013.html,I was out with the morning sun \r\nCouldn't s...
9,ABBA,Crying Over You,/a/abba/crying+over+you_20177611.html,I'm waitin' for you baby \r\nI'm sitting all ...

In [5]:
df.tail(10)

,artist,song,link,text
57640,Zebrahead,The Setup,/z/zebrahead/the+setup_10198494.html,Lie to me \r\nTell me that everything will be...
57641,Ziggy Marley,Freedom Road,/z/ziggy+marley/freedom+road_20531174.html,"That's why I'm marching, yes, I'm marching, \..."
57642,Ziggy Marley,Friend,/z/ziggy+marley/friend_20673508.html,[Chorus] \r\nI wanna thank you for the things...
57643,Ziggy Marley,G7,/z/ziggy+marley/g7_20531173.html,Seven richest countries in the world \r\nThem...
57644,Ziggy Marley,Generation,/z/ziggy+marley/generation_20531171.html,Many generation have passed away \r\nFighting...
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [6]:
df.shape

(57650, 4)

In [7]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [8]:
df=df.drop('link',axis = 1).reset_index(drop=True)

In [9]:
df.head(10)

,artist,song,text
0,ABBA,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante","Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,Making somebody happy is a question of give an...
5,ABBA,Burning My Bridges,"Well, you hoot and you holler and you make me ..."
6,ABBA,Cassandra,Down in the street they're all singing and sho...
7,ABBA,Chiquitita,"Chiquitita, tell me what's wrong \r\nYou're e..."
8,ABBA,Crazy World,I was out with the morning sun \r\nCouldn't s...
9,ABBA,Crying Over You,I'm waitin' for you baby \r\nI'm sitting all ...

In [10]:
df['text'][0]

"Look at her face, it's a wonderful face  \r\nAnd it means something special to me  \r\nLook at the way that she smiles when she sees me  \r\nHow lucky can one fellow be?  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?  \r\n  \r\nAnd when we go for a walk in the park  \r\nAnd she holds me and squeezes my hand  \r\nWe'll go on walking for hours and talking  \r\nAbout all the things that we plan  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"

In [11]:
df = df.sample(10000).reset_index(drop=True)

In [12]:
df.shape

(10000, 3)

Text preprocessing or Text Cleaing

In [13]:
df['text']=df['text'].str.lower()

In [14]:
# Only lowercasing and removing newlines, keep words for vectorization

In [15]:
df['text'] = df['text'].replace(r'\n', ' ', regex=True)

In [16]:
df.head(10)

,artist,song,text
0,Ozzy Osbourne,Bomber Can't Be Bombays,listen my son \r one thing i've learned \r a...
1,Lenny Kravitz,God Gave My Everything,you can see it in a clear blue sky \r you can...
2,Procol Harum,This Old Dog,drank a little too much wine last night \r dr...
3,The Killers,Show You How,you have one saved message \r to listen to yo...
4,Robbie Williams,Don't Do Love,i could be an animal for many years to come \...
5,Ween,Marble Tulip Juicy Tree,"i don't know you you are, i don't know who you..."
6,Wet Wet Wet,Sweet Surrender,"hey little fella, get your show together \r i..."
7,Various Artists,3 Doors Down - When I'm Gone,there's another world inside of me \r that yo...
8,Uriah Heep,Roller,oh where is she woman \r she's only here for ...
9,Rush,Workin' Them Angels,"driving away to the east, and into the past \..."

In [17]:
import nltk
from nltk.stem.porter import PorterStemmer

nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\RAKESH
[nltk_data]     NAIDU\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [18]:
stemmer=PorterStemmer()

In [19]:
def token(txt):
  token=nltk.word_tokenize(txt)
  a=[stemmer.stem(w) for w in token]
  return " ".join(a)

In [20]:
token("you are beautiful, beauty")

'you are beauti , beauti'

In [21]:
# Apply stemming and tokenization, and save back to df['text']
df['text'] = df['text'].apply(lambda x: token(x))

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity # Correct the module name here

In [23]:
tfid=TfidfVectorizer(analyzer='word',stop_words='english')

In [24]:
matrix = tfid.fit_transform(df['text'])

In [25]:
print('Sample of df["text"] after preprocessing and stemming:')
print(df['text'].head(20))

Sample of df["text"] after preprocessing and stemming:
0     listen my son one thing i 've learn and i know...
1     you can see it in a clear blue sky you can see...
2     drank a littl too much wine last night drank a...
3     you have one save messag to listen to your mes...
4     i could be an anim for mani year to come it wo...
5     i do n't know you you are , i do n't know who ...
6     hey littl fella , get your show togeth i wa li...
7     there 's anoth world insid of me that you may ...
8     oh where is she woman she 's onli here for the...
9     drive away to the east , and into the past his...
10    the neon light are shine on me again i walk th...
11    the harder we play the faster we fall when we ...
12    six cheap peopl in an empti hotel everi last o...
13    i touch you onc too often now i do n't know wh...
14    yeah , elect time 's comin ' who you gon ' vot...
15    whoo ! [ hook : ] memph ' bleek alway smokin t...
16    alway and forev each moment with you is just l...
17    dark are the street , gloom 's creep out of th...
18    waktu kau lewat aku sedang mainkan gitar sebua...
19    some see life as a broken promis some see life...
Name: text, dtype: object

In [26]:
# Filter out empty or null text rows before vectorization
df = df[df['text'].notnull() & (df['text'].str.strip() != '')]

In [27]:
similar=cosine_similarity(matrix)

In [28]:
similar[0]

array([1.        , 0.01349346, 0.02759458, ..., 0.00731301, 0.00329337,
       0.03731944])

Recommender Function

In [32]:
def recommender(song_name, df):
    if 'song' not in df.columns:
        print("Error: 'song' column not found in DataFrame.")
        return []
    
    if song_name not in df['song'].values:
        print(f"Song '{song_name}' not found in DataFrame.")
        return []
    
    idx = df[df['song'] == song_name].index[0]
    
    distance = sorted(list(enumerate(similar[idx])), reverse=True, key=lambda x: x[1])
    
    song = []
    
    for s_id in distance[1:21]:
        song.append(df.iloc[s_id[0]]['song'])
    
    return song

# Example usage:
print(recommender("Can't You See", df))

["You Can't Touch This", "I Can't Let Go", 'I Will Always Want You', 'Girls And Boys', 'Dark Fantasy', 'Here Comes The Hammer', 'Gypsy', "I Can't Live With You", 'Days Like These', 'How', 'Never', 'I Am Waiting', 'If You Leave Me Now', "Can't Stop", 'Notice Me', "That's Alright With Me", 'Midnight Blue', "I'll Be Good For You", 'Had A Dream', 'Baby']

In [33]:
# Try the recommender with another song name
print(recommender('God Gave My Everything', df))

['God Gave You', 'But, Honestly', 'I Gave Everything (That A Girl In Love Should Never Give)', 'Live Forever', 'My God', 'Everything', 'Never Stop', 'Last Christmas', 'I Can Give You Everything', 'If You Really Knew', 'God Put A Smile Upon Your Face', 'Cry For Home', 'All For Love', 'God Is Love', 'I Feel Sorry For Him', 'Jihad', 'All I Do', 'Awesome God', 'I Gave It Up (When I Fell In Love)', 'Rooftop']